# Services definition override for development

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-dev:${IMAGES_TAG:-latest}
    build:
      target: app_dev
      args:
        PORT: "${HTTP_DOCKER_PORT:-8080}"
    # Deploy
    ports: !override
      - "${HTTP_PORT:-8080}:${HTTP_DOCKER_PORT:-8080}" # HTTP
    develop:
      watch:
        # Docker image
        - action: rebuild
          path: ./app/Dockerfile
        # Application build files
        - action: rebuild
          path: ./app/app/package.json
        - action: rebuild
          path: ./app/app/package-lock.json
        # Application configuration
        - action: sync+restart
          path: ./app/app/astro.config.mjs
          target: /app/astro.config.mjs
        # Application source code
        - action: sync
          path: ./app/app
          target: /app
          ignore:
            - node_modules/
